#!/usr/bin/env bash
# note-index.sh — regenerate notes/INDEX.md from all saved notes
# Usage: bash scripts/note-index.sh
# Called automatically after every note save

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

NOTES_DIR="$REPO_DIR/notes"
INDEX_FILE="$REPO_DIR/notes/INDEX.md"

# Collect all note files sorted by filename descending (newest first)
_tmp_files=$(mktemp)
find "$NOTES_DIR" -name "*.md" ! -name ".gitkeep" ! -name "INDEX.md" | sort -r > "$_tmp_files"
mapfile -t FILES < "$_tmp_files"
rm -f "$_tmp_files"

TOTAL=${#FILES[@]}

# ---- helpers ----------------------------------------------------------------

# Extract a YAML frontmatter field value: parse_field <field> <file>
parse_field() {
  local field="$1" file="$2"
  # Match "field: value" inside the --- block at the top of the file
  awk '/^---/{found++; next} found==1 && /^'"$field"':/{sub(/^[^:]+: */,""); print; exit}' "$file"
}

# Build a markdown link for a note file
note_link() {
  local file="$1"
  local title date tags rel_path
  title=$(parse_field "title" "$file")
  date=$(parse_field "date" "$file")
  tags=$(parse_field "tags" "$file")
  rel_path="${file#$NOTES_DIR/}"  # strip leading notes dir prefix

  # Format tags as inline chips if present
  local tag_str=""
  if [[ -n "$tags" && "$tags" != "[]" ]]; then
    tag_str=$(echo "$tags" | tr -d '[]' | sed 's/,/ /g' | xargs -n1 printf '`%s` ')
  fi

  # Fallback: derive title from filename if frontmatter missing
  if [[ -z "$title" ]]; then
    title=$(basename "$file" .md | sed 's/^[0-9-]*-//' | tr '-' ' ')
  fi
  if [[ -z "$date" ]]; then
    date=$(basename "$file" .md | grep -oP '^\d{4}-\d{2}-\d{2}' || echo "—")
  fi

  echo "- **${date}** [${title}](${rel_path}) ${tag_str}"
}

# ---- group by type ----------------------------------------------------------

declare -A TYPE_LINES
TYPES=("meeting" "minutes" "discussion" "instruction" "quick")
declare -A TYPE_LABELS=(
  [meeting]="Meetings"
  [minutes]="Meeting Minutes"
  [discussion]="Discussions"
  [instruction]="Work Instructions"
  [quick]="Quick Notes"
)

for t in "${TYPES[@]}"; do
  TYPE_LINES[$t]=""
done
TYPE_LINES[other]=""

for f in "${FILES[@]}"; do
  type=$(parse_field "type" "$f")
  [[ -z "$type" ]] && type="other"
  line=$(note_link "$f")
  if [[ -v TYPE_LINES[$type] ]]; then
    TYPE_LINES[$type]+="${line}"$'\n'
  else
    TYPE_LINES[other]+="${line}"$'\n'
  fi
done

# ---- count open actions -----------------------------------------------------

OPEN_ACTIONS=0
for f in "${FILES[@]}"; do
  count=$(grep -cP '\|\s.*\|\s.*\|\s.*Open' "$f" 2>/dev/null || true)
  OPEN_ACTIONS=$((OPEN_ACTIONS + count))
done

# ---- write INDEX.md ---------------------------------------------------------

{
  echo "# Notes Index"
  echo ""
  echo "> Auto-generated by \`scripts/note-index.sh\`. Do not edit manually."
  echo ""
  echo "**Total notes:** ${TOTAL} &nbsp;|&nbsp; **Open actions:** ${OPEN_ACTIONS}"
  echo ""
  echo "---"
  echo ""

  # Quick search hint
  echo "**Search:** \`bash scripts/note-search.sh \"keyword\"\`"
  echo "**Open actions:** \`/note-actions\`"
  echo ""
  echo "---"
  echo ""

  for t in "${TYPES[@]}"; do
    lines="${TYPE_LINES[$t]}"
    if [[ -n "$lines" ]]; then
      count=$(echo "$lines" | grep -c '^-' || true)
      echo "## ${TYPE_LABELS[$t]} (${count})"
      echo ""
      echo "$lines"
    fi
  done

  if [[ -n "${TYPE_LINES[other]}" ]]; then
    echo "## Other"
    echo ""
    echo "${TYPE_LINES[other]}"
  fi

  echo "---"
  echo "*Updated: $(date '+%Y-%m-%d %H:%M')*"
} > "$INDEX_FILE"

echo "Index updated: $INDEX_FILE (${TOTAL} notes, ${OPEN_ACTIONS} open actions)"
